apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-tester-sa
rules:
- apiGroups:  # This is required by the agent to query the Kubelet API.
  - ""
  resources:
  - nodes/spec
  verbs:
  - get